export const routes = {
  login: "/login",
  signup: "/signup",
  resetPassword: "/reset-password",
  pending: "/pending",
  suspended: "/suspended",
  student: {
    root: "/student",
    jobs: "/student/jobs",
    content: "/student/content",
    favorites: "/student/favorites",
    applications: "/student/applications",
    schedules: "/student/schedules",
    news: "/student/content/news",
    board: "/student/content/board",
    resources: "/student/content/resources",
    surveys: "/student/surveys",
    profile: "/student/profile",
  },
  teacher: {
    root: "/teacher",
    students: "/teacher/students",
    jobs: "/teacher/jobs",
    schedules: "/teacher/schedules",
    content: "/teacher/content",
  },
  employment: {
    root: "/employment",
    jobs: "/employment/jobs",
    companies: "/employment/companies",
    applications: "/employment/applications",
    students: "/employment/students",
    schedules: "/employment/schedules",
    content: "/employment/content",
    surveys: "/employment/surveys",
    notifications: "/employment/notifications",
  },
  admin: {
    root: "/admin",
  },
} as const;
